### PR TITLE
Adding an option to use a percentage of the system memory for pgtuning

### PR DESCRIPTION
**Pull request by gilesw**

### CODE REVIEW

**Comment by gilesw** [comment]
I haven't removed pgtune but it might make sense to remove it given that if it runs with Postgresql 9.6 the settings it creates will cause Postgres to not startup and for versions <9.3 many of the memory settings will not work because the kernel SHM settings are not adjusted.

**Comment by gilesw** [comment]
sysctl reload is not implemented for postgresql <9.3 but could be, either by a shell command or waiting for this feature, https://github.com/ansible/ansible/issues/18818

**Comment by gilesw** [comment]
I'm not aware of a way of testing if a module exists or not. 

ERROR: postgresql_tune is not a legal parameter in an Ansible task or handler
The command '/bin/sh -c ansible-playbook -i inventory -c local --become tests/playbook.yml' returned a non-zero code: 1

**Comment by otakup0pe** [comment]
This is kind of cool. I wonder if there is a way we can embed the module in our ansible role....

**Comment by gilesw** [comment]
@otakup0pe the ansible module has been improved already. I don't think the original author would have an issue with you putting it into a /library directory of your role, I don't know whether that gets activated automatically though. Certainly pgtune is pretty much broken with 9.3 upwards.

**Comment by otakup0pe** [comment]
If you want to reach out to the author and ask and mix it into this PR, I am OK with that.

**Comment by gilesw** [comment]
Sure I'm still waiting for a pull someone made to my fork to get back into his repo so I'll ask when he gets round to that.

**Comment by gclough** [comment]
In #301, I've proposed a new format for tuning that is pure Ansible, and avoids the use of pgtune altogether.  I've rolled in a new change that adds the `postgresql_tuning_memory_percent` variable, which should do what you want.

**Comment by gclough** [comment]
Hi @gilesw, I know it's been quite some time... but I'm trying to clear the backlog in this project.  This build fails, so I can't merge it.

If you could submit a new version that passes, I'd be happy to review it and merge.  I tried to sidestep pgtune entirely with #301, but that's got issues with the way Ansible handles variable inheritance.

If it's no longer needed, could you please close this PR?

**Comment by gilesw** [comment]
@gclough I used your code in the end. I moved it into the defaults/main.yml with a couple of changes. I'm happy with always tuning myself but I guess not everyone would be. So I'll close this one off and eventually that ansible defaults change will get looked at.

**Comment by gclough** [comment]
Super, thanks.  I hope to get my stuff merged in, or somehow fixed to work globally... then hopefully you can roll any or your changes back into the core of this role.

**Pull request closed without merging**
