### PR TITLE
Fix #445: PSQL tasks fails when postgresql_port != 5432 (default value)

### LINKED ISSUE #445: PSQL tasks fails when `postgresql_port` != 5432 (default value)
When using `postgresql_port` with custom value ( != 5432), tasks relying on psql fails with message:
```
psql: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
```
It seem that psql client don't get the correct socket name based on the actual configured port, which is 5612 in my case:
```
>ls -al /var/run/postgresql/
total 8
drwxrwsr-x.  2 postgres postgres 100 Sep  2 12:48 .
drwxr-xr-x. 24 root     root     820 Sep  2 13:09 ..
-rw-r--r--.  1 postgres postgres   6 Sep  2 12:48 10-data.pid
srwxrwxrwx.  1 postgres postgres   0 Sep  2 12:48 .s.PGSQL.5612
-rw-------.  1 postgres postgres  66 Sep  2 12:48 .s.PGSQL.5612.lock
```

I think a simple fix would be to add PGPORT env var to each task relaying on psql client:

for example:
```
# Check database version
- name: PostgreSQL | Check database version
  shell: >
    psql --quiet --tuples-only --command="select substring(version(),'[^\s]+\s+[^\s]+');" | sed 's/^ //'
  become: yes
  become_user: "{{ postgresql_service_user }}"
  changed_when: false
  failed_when: postgresql_database_version.stdout == ""
  register: postgresql_database_version
  check_mode: no  
  environment:
    - PGPORT: "{{ postgresql_port }}"
```

Temporary fix, add environment PGPORT to the playbook step calling the postgresl role:

```
- name: "Provision Postgresql"
  hosts: dbs
  become: true
  roles:
    - anxs.postgresql
  environment:
    - PGPORT: "{{ postgresql_port }}"
```

Envs:
- OS: Centos 7
- Ansible 2.8
- Role version: v1.11.1

### PR DESCRIPTION
**Pull request by lrk**
I added PGPORT environment variable for each task using psql client where it need to connect to the database.
I also change the `postgresql_port` in tests to check that everything work fine.

### CODE REVIEW

**Comment by lrk** [comment]
there is an error unrelated to my modification in CI tests for  Python: 2.7 on fedora:27-builded image
```
fatal: [postgresql-9.5]: FAILED! => {"changed": false, "cmd": "dnf install -y python2-dnf", "failed": true, "msg": "Error: Unable to find a match: python2-dnf", "rc": 1, "stderr": "Error: Unable to find a match: python2-dnf\n", "stderr_lines": ["Error: Unable to find a match: python2-dnf"], "stdout": "Last metadata expiration check: 0:01:07 ago on Tue Sep  3 07:44:35 2019.\nNo match for argument: python2-dnf\n", "stdout_lines": ["Last metadata expiration check: 0:01:07 ago on Tue Sep  3 07:44:35 2019.", "No match for argument: python2-dnf"]}
fatal: [postgresql-11]: FAILED! => {"changed": false, "cmd": "dnf install -y python2-dnf", "failed": true, "msg": "Error: Unable to find a match: python2-dnf", "rc": 1, "stderr": "Error: Unable to find a match: python2-dnf\n", "stderr_lines": ["Error: Unable to find a match: python2-dnf"], "stdout": "Last metadata expiration check: 0:01:07 ago on Tue Sep  3 07:44:35 2019.\nNo match for argument: python2-dnf\n", "stdout_lines": ["Last metadata expiration check: 0:01:07 ago on Tue Sep  3 07:44:35 2019.", "No match for argument: python2-dnf"]}
fatal: [postgresql-10]: FAILED! => {"changed": false, "cmd": "dnf install -y python2-dnf", "failed": true, "msg": "Error: Unable to find a match: python2-dnf", "rc": 1, "stderr": "Error: Unable to find a match: python2-dnf\n", "stderr_lines": ["Error: Unable to find a match: python2-dnf"], "stdout": "Last metadata expiration check: 0:01:08 ago on Tue Sep  3 07:44:35 2019.\nNo match for argument: python2-dnf\n", "stdout_lines": ["Last metadata expiration check: 0:01:08 ago on Tue Sep  3 07:44:35 2019.", "No match for argument: python2-dnf"]}
fatal: [postgresql-9.6]: FAILED! => {"changed": false, "cmd": "dnf install -y python2-dnf", "failed": true, "msg": "Error: Unable to find a match: python2-dnf", "rc": 1, "stderr": "Error: Unable to find a match: python2-dnf\n", "stderr_lines": ["Error: Unable to find a match: python2-dnf"], "stdout": "Last metadata expiration check: 0:01:08 ago on Tue Sep  3 07:44:35 2019.\nNo match for argument: python2-dnf\n", "stdout_lines": ["Last metadata expiration check: 0:01:08 ago on Tue Sep  3 07:44:35 2019.", "No match for argument: python2-dnf"]}
fatal: [postgresql-9.4]: FAILED! => {"changed": false, "cmd": "dnf install -y python2-dnf", "failed": true, "msg": "Error: Unable to find a match: python2-dnf", "rc": 1, "stderr": "Error: Unable to find a match: python2-dnf\n", "stderr_lines": ["Error: Unable to find a match: python2-dnf"], "stdout": "Last metadata expiration check: 0:01:08 ago on Tue Sep  3 07:44:35 2019.\nNo match for argument: python2-dnf\n", "stdout_lines": ["Last metadata expiration check: 0:01:08 ago on Tue Sep  3 07:44:35 2019.", "No match for argument: python2-dnf"]}
```

**Comment by lrk** [comment]
i think it's related to the ansible dnf module requirements:
https://docs.ansible.com/ansible/latest/modules/dnf_module.html#dnf-module
```
The below requirements are needed on the host that executes this module.

python >= 2.6
python-dnf
for the autoremove option you need dnf >= 2.0.1”
```

why not using the generic **package** module instead ?

**Comment by gclough** [comment]
Could you rebase this against master (with #447), as Fedora was killing the build

**Comment by lrk** [comment]
@gclough sorry i messed up my fork, so i re-create a new PR: #448

**Pull request closed without merging**
