### PR TITLE
verbatim password_encryption

### PR DESCRIPTION
**Pull request by barda**
For 11 copy password_encryption configuration variable: valid values are md5 and scram-sha-256

### CODE REVIEW

**Comment by egmont1227** [comment]
duplicated by #460 and #368, i propose to close this one

**Comment by maglub** [comment]
PR #460 has a suboptimal solution:

```
password_encryption = {{ 'md5' if postgresql_password_encryption != 'scram-sha-256' else 'scram-sha-256' }}     # md5 or scram-sha-256
```

I agree with the solution in this PR, but this PR touches too many other things:

```
password_encryption = {{ postgresql_password_encryption if postgresql_password_encryption else 'off' }}		# md5 or scram-sha-256
```

Valid values are:

* `""`
* `on`
* `md5`
* `scram-sha-256`

**Comment by robustq** [comment]
Can be closed as #460 was merged in, though @barda the privileges piece is interesting, and you should definitely consider moving those changes to another pull request

**Comment by egmont1227** [comment]
Agree. Please adjust your changes to privileges only (merge master changes for password encryption) and rename this PR

or close this one and open another one for the privileges part.

**Comment by gclough** [comment]
@barda , thanks for the work, and based on the discussion above I will close this PR, but we would appreciate one specifically on the password fix.

If you can keep Pull Requests limited to only a single fix, then it makes them easier to approve/reject them individually.

**Pull request closed without merging**
