### PR TITLE
Load extensions with `postgresql_ext` instead of `psql`

### LINKED ISSUE #292: Create extensions with `postgresql_ext` instead of using `psql`
Ansible has a native module to handle PostgreSQL extensions called `postgresql_ext`:

http://docs.ansible.com/ansible/latest/postgresql_ext_module.html

We should use that, instead of calling `shell`, which then calls `psql`.

### PR DESCRIPTION
**Pull request by gclough**
Fixes #292.

Convert from using `psql` to using the Ansible module `postgresql_ext`, which I suspectis a more reliable method.

### CODE REVIEW

**Comment by gclough** [comment]
@sebalix ... done (plus a couple of other popular ones to boot).  The results were:

```
TASK [ANXS.postgresql : PostgreSQL | Add extensions to the databases] **********
changed: [postgresql-9.3] => (item=({u'db': u'foobar'}, u'adminpack'))
changed: [postgresql-9.6] => (item=({u'db': u'foobar'}, u'adminpack'))
changed: [postgresql-9.5] => (item=({u'db': u'foobar'}, u'adminpack'))
changed: [postgresql-9.4] => (item=({u'db': u'foobar'}, u'adminpack'))
changed: [postgresql-9.3] => (item=({u'db': u'foobar'}, u'pgcrypto'))
changed: [postgresql-9.6] => (item=({u'db': u'foobar'}, u'pgcrypto'))
changed: [postgresql-9.4] => (item=({u'db': u'foobar'}, u'pgcrypto'))
changed: [postgresql-9.5] => (item=({u'db': u'foobar'}, u'pgcrypto'))
changed: [postgresql-9.3] => (item=({u'db': u'foobar'}, u'unaccent'))
changed: [postgresql-9.6] => (item=({u'db': u'foobar'}, u'unaccent'))
changed: [postgresql-9.5] => (item=({u'db': u'foobar'}, u'unaccent'))
changed: [postgresql-9.4] => (item=({u'db': u'foobar'}, u'unaccent'))
```

**Comment by sebalix** [comment]
@gclough I see a merge commit in your branch, instead you should rebase your branch on top of master to have a clean history, only your first and third commit matters here.

**Comment by gclough** [comment]
Thanks again @sebalix .  It seems I've been using git a little "sub optimally" (as my sysadmin puts it... but he's being polite).  I've tried to merge things back in, but I'll have to start from scratch.  If possible, can I do this for all new PR's, and leave the ones that I've already done stand as-is?

**Comment by sebalix** [comment]
No problem!
Regarding this PR, I push another one (with your commits) to replace yours. Are you OK to close this one?

**Comment by gclough** [comment]
Superseded by #307 with squashed commits by @sebalix ... @UnderGreen , can you review/approve that one instead?

**Pull request closed without merging**
