### PR TITLE
Updated to use "import_tasks" instead of "include"

### LINKED ISSUE #290: The use of 'include' for tasks has been deprecated.  Need to swap to 'include_tasks', or 'import_tasks'
Warning message:

`[DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated. Use 
'import_tasks' for static inclusions or 'include_tasks' for dynamic inclusions. This 
feature will be removed in a future release. Deprecation warnings can be disabled by 
setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: include is kept for backwards compatibility but usage is 
discouraged. The module documentation details page may explain more about this rationale.. 
This feature will be removed in a future release. Deprecation warnings can be disabled by 
setting deprecation_warnings=False in ansible.cfg.`

Ansible version:

`[ansible@localhost conf.d]$ ansible --version
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]`

### PR DESCRIPTION
**Pull request by gclough**
Converted to use `import_tasks` instead of `include`, to remove the Depracation warning.  Fixes #290

### CODE REVIEW

**Comment by gclough** [comment]
Thanks @sebalix ... I was just tracking down what broke in build.  I can update it to v2.4... but won't that cause pain for other users that may still be using v2.3 and earlier?  I'll check in that new code to upgrade it all to v2.4, but I'd understand if you prefer not to merge it as it will bump the minimum requirement from v1.9 to v2.4.

**Comment by sebalix** [comment]
I am not a maintainer of the project, I can't merge anyway :)
Regarding the support for 2.4 and superior, I'm personally in favor (we already use the 2.4 internally), so :+1:

**Comment by gclough** [comment]
Thanks for the help @sebalix .  Do you know how long it normally takes for pull requests to get merged?  I've got others pending, and more in the pipeline...

**Comment by sebalix** [comment]
@erdenezul @otakup0pe @jlozadad are you OK to set the minimum Ansible to 2.4? And to merge this PR?

**Comment by jlozadad** [comment]
agreed. 2.4 should be used. lgtm

**Comment by sebalix** [comment]
Someone to proceed with the merge? :)

**Comment by jlozadad** [comment]
wish I could merge :package:

**Pull request merged**
