### PR TITLE
Fix PostGIS install

### LINKED ISSUE #251: POSTGIS extension fails
When setting up a production instance I ran into this issue with the postgis task.  The error would report that `item is not found` from the file `postgresql/tasks/extensions/postgis.yml`

We got it working by changing the path in that above file with a step up in the relative paths.  

Before 
```
# file: postgresql/tasks/extensions/postgis.yml

- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution_release }}.yml"
    - ".../vars/empty.yml"

- name: PostgreSQL | Extensions | Make sure the postgis extensions are installed
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
    cache_valid_time: "{{apt_cache_valid_time | default (3600)}}"
  with_items: "{{ postgresql_ext_postgis_deps }}"
  notify:
    - restart postgresql
```

After (fix applied)
```
# file: postgresql/tasks/extensions/postgis.yml

- include_vars: "{{ item }}"
  with_first_found:
    - "../../vars/{{ ansible_distribution_release }}.yml"  <<<<<<<<<<<<<< Added ../ to the path
    - "../../vars/empty.yml"                                               <<<<<<<<<<<<<< Added ../ to the path

- name: PostgreSQL | Extensions | Make sure the postgis extensions are installed
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
    cache_valid_time: "{{apt_cache_valid_time | default (3600)}}"
  with_items: "{{ postgresql_ext_postgis_deps }}"
  notify:
    - restart postgresql
```

### PR DESCRIPTION
**Pull request by gclough**
Fixes #251, and gives sensible defaults (the latest version) of PostGIS for each different version of PostgreSQL

I've also added the extension to the travis tests, so it should get exercised regularly from now on

### CODE REVIEW

**Comment by gclough** [comment]
Oh no... @sebalix , that's just made a complete hash of it.  The rebase seems to be taking in other changes and merging them into this PR.  <sigh>

Back to the drawing board...

**Comment by jlozadad** [comment]
looks like this PR also failing for me cause installing `epel-release` is not done before this is installed. I opened this issue https://github.com/ANXS/postgresql/issues/326 so we can make that change. I think we should fix that first.

**Comment by gclough** [comment]
Closing to trigger Travis...

**Comment by jlozadad** [comment]
need git rebase

**Comment by gclough** [comment]
@jlozadad , I've merged this to master, but it could definitely do with a review to ensure it's solid.  It passes the automated tests, so that's a good sign.

**Comment by jlozadad** [comment]
besides git rebase what else is needed here ?

**Pull request closed without merging**
