### PR TITLE
Multiple vm Vagrant, to promote more cross-platform testing

### LINKED ISSUE #389: Vagrant only works with one OS at a time
Currently the Vagrant config only provisions a single VM:

```
machine.vm.box = "fedora/27-cloud-base"
```

If we are supporting all of these OS's, then we should provision ALL of them, right?

### PR DESCRIPTION
**Pull request by gclough**
Fixes #389 , but also commented out #390, and #391 because they are broken.

Now when you run `vagrant up`, it creates all of the VM's we support (aside from the two broken ones listed above), and runs the role against them.

This is probably something for @jlozadad to check/verify.

### CODE REVIEW

**Comment by otakup0pe** [comment]
Oh this is pretty neat! This is getting closer to representing what we do in Travis. Been thinking about molecule recently too...

**Comment by gclough** [comment]
Thanks @otakup0pe , that was the plan.  Too many of my PR's failed during the Travis testing, so I wanted to make sure I had a local environment that I could verify things in before sending it to you guys.

How can we get this reviewed and merged, so that others can benefit?

I've also done a bit of a "howto" on setting up a VM with vagrant, virtualbox, and getting it all to run.  I'll do a separate PR for that once I've knocked it into shape.

**Comment by otakup0pe** [comment]
If @jlozadad doesn't have time to review, I can make time this weekend. As a side note, please let me know if you are interested in helping maintain this role.

**Comment by gclough** [comment]
Hi @otakup0pe, sure I'm happy to help maintain it.  I have a lot of experience in PostgreSQL, but less so with Ansible... but I do build and manage all of our PostgreSQL databases using a fork of this role with a bunch of local enhancements. I would love to contribute them all back into this role, as I really don't want a local fork.

But first, how can we merge, fix, or reject the 11 outstanding PR's I have?  Some of them have gone rotten, but I'm happy to rebase them if someone has the time to review and merge:

https://github.com/ANXS/postgresql/pulls/gclough

**Pull request merged**
