### PR TITLE
Add support for PostgreSQL 10

### PR DESCRIPTION
**Pull request by merifri**
- Add configuration template for PostgreSQL 10
- Update variables in defaults/main.yml
- [RedHat] Fix path to postgresql*-check-db-dir script

  > `postgresql{{ version }}-check-db-dir` replaced with `postgresql-{{ version }}-check-db-dir`

- Fix vagrant box name for centos
- Update .travis.yml

### CODE REVIEW

**Comment by RoelAdriaans-B-informed** [comment]
Tested on LXC containers with ansible 2.4.2.0, ubuntu 16.04 👍 ,

**Comment by taybin** [comment]
What's the status of this?

**Comment by merifri** [comment]
Tested on ubuntu (14.04, 16.04), centos (6, 7), debian (8, 9).
We actively use this branch with ansible (2.3.x and 2.4.x) on ubuntu (14.04, 16.04), debian (8, 9).

**Comment by RoelAdriaans-B-informed** [comment]
Is this ANXS.postgresql project still active?
Last commit was in July, and there have been open issues for months?

**Comment by taybin** [comment]
Is this redundant with #267 passing tests now?

**Comment by jlozadad** [comment]
there was another PR merge earlier today after it had significant changes made and tested. i wil close this PR.  please submit another PR if we missed something. ty.

**Pull request closed without merging**
