### PR TITLE
Add vagrantfile and idempotence test

### PR DESCRIPTION
**Pull request by farridav**
- Add VagrantFile
- Add idempotence test
- Add inventory for vagrant

Following suit from https://github.com/ANXS/nodejs/pull/18 cheers @otakup0pe

### CODE REVIEW

**Comment by otakup0pe** [comment]
LGTM :sparkling_heart: 

I can't test till tonight though.

**Comment by farridav** [comment]
@pjan I can move this into a submodule if need be, please ping me when you have setup another repo and ill add it to this PR.. thanks

**Comment by pjan** [comment]
LGTM :octocat: 

As per feedback, feel free to merge into the role. Great work @farridav!

**Comment by farridav** [comment]
@otakup0pe please merge in when ready, ill then make similar PR's to the others

**Pull request merged**
