### PR TITLE
[9.5] Added support for PostgreSQL 9.5

### PR DESCRIPTION
**Pull request by zamotivator**

### CODE REVIEW

**Comment by sebalix** [comment]
Great. I would like the PR #102 merged before this one as it updates .travis.yml a bit. Then, the current one could be rebased+updated to enable Travis on Pg 9.5. @farridav?

**Comment by zamotivator** [comment]
I made changes exactly as described here: https://github.com/sebalix/postgresql/blob/7e4a1063805ce6072ec64f6e49733c4e92610a9d/templates/HOWTO.postgresql.conf
except os (I used CentOS 7)

**Comment by zamotivator** [comment]
I updated pull request, renamed `wal_retrieve_retry_interval` to `postgresql_wal_retrieve_retry_interval`, added comments about the version of PostgreSQL

**Comment by sebalix** [comment]
Nice! It might be better to put the ">= 9.5" indication on the same line, as it can be misunderstood for the options that follow just after (e.g. `postgresql_wal_log_hints`)

**Comment by zamotivator** [comment]
Will do in half-hour

**Comment by sebalix** [comment]
You can edit .travis.yml if you want to activate the CI on the 9.5 version. No matter which PR is merged at first, if it is yours I will update mine (#102), that's not a problem.

**Comment by zamotivator** [comment]
Ooops, we have the problem. I will check & fix Ubuntu

**Comment by zamotivator** [comment]
Seems like 9.5 unavailable under Ubuntu 12.04.
Trying 14.04 (LTS too)

**Comment by zamotivator** [comment]
Seems to be problem with repository line: http://raonyguimaraes.com/installing-postgresql-9-5-on-linux/
Fixed, checking

**Comment by sebalix** [comment]
The package exists for Ubuntu Precise though http://apt.postgresql.org/pub/repos/apt/dists/precise-pgdg/9.5/binary-amd64/Packages.

You have this role working with PostgreSQL 9.5 locally?
Maybe a conflict with the Travis environment, as it is already shipped with the PostgreSQL APT repository (that's why I have removed it in #102 https://github.com/ANXS/postgresql/pull/102/files#diff-354f30a63fb0907d4ad57269548329e3R12 to start on a clean base)

**Comment by zamotivator** [comment]
>>> You have this role working with PostgreSQL 9.5 locally?

Under CentoS 7 it works perfectly

>>> Maybe a conflict with the Travis environment, as it is already shipped with the PostgreSQL APT repository 

I do not know. I am investigating on own Ubuntu 12.04 instance in the DigitalOcean. Will know you about results

**Comment by zamotivator** [comment]
Hm, it works perfectly on own Ubuntu image. Seems to be something broken in the Travis...

**Comment by sebalix** [comment]
As it's related to myspell/unspell packages, it's maybe due to the locale configuration. I will make some tests from my side too.

**Comment by zamotivator** [comment]
Do not merge please, I want to rebase commits

**Comment by zamotivator** [comment]
So, @sebalix  I investigated the reason.
Travis image includes PostgreSQL 9.1, 9.2, 9.3, and 9.4.
As result, installation of PostgreSQL 9.5 conflicts with available installations.
I added (and I will fix more) remove of PostgreSQL installation, and after that everything works fine.

I also want investigate another workaround - install postgresql-common explicitly.
I will inform you when I done

**Comment by sebalix** [comment]
Well, either we merge #102 before as it removes the installed PostgreSQL servers, or you integrate these lines https://github.com/ANXS/postgresql/pull/102/files#diff-354f30a63fb0907d4ad57269548329e3R12 in your PR.

**Comment by zamotivator** [comment]
I integrated these lines to .travis.yml
Checking

**Comment by zamotivator** [comment]
@sebalix  I did it. You can merge pull request :)

**Comment by zamotivator** [comment]
No, stop. I removed some lines from default, need to remove. Several minutes.

**Comment by zamotivator** [comment]
No, everything is fine. Please merge it.

**Comment by sebalix** [comment]
Nice job! But I have no write access on this repository. 
@farridav or @pjan can you review this please?

**Comment by zamotivator** [comment]
Any updates?

**Comment by farridav** [comment]
Looking at this today :)

**Comment by farridav** [comment]
Looks good to me, and working on all three versions as expected :) happy to bring it in

**Comment by farridav** [comment]
A new tag has been made, so this should also be available in ansible galaxy

**Pull request merged**
