### PR TITLE
Add support to install variable extensions

### PR DESCRIPTION
**Pull request by andreychernih**

### CODE REVIEW

**Comment by rud** [comment]
Just thought this was missing, the change looks good to me (though I am Ansible newb). Is there a maintainer around to maybe merge this?  

@andreychernih I think a deprecation / warning in the README is in order here as it's a breaking change.

**Comment by soupdiver** [comment]
Since there is a lot of repeated code for adding the extensions where the only change is the extensions name I like the idea.
Could you update the PR against the latest master?

@farridav @otakup0pe @pjan What's your opinion on this?

**Comment by farridav** [comment]
Seems sane to me, looks like it needs a rebase against master first.. and how about that breaking change warning in the README @andreychernih?

**Comment by farridav** [comment]
Hi @andreychernih https://github.com/ANXS/postgresql/pull/96 has just been merged in, and i believe it satisfies your requirements.. to that end, I'm closing this PR... if your requirements are not met by this, feel free to shout :)

**Pull request closed without merging**
