### PR TITLE
Added PostgreSQL 14 support

### PR DESCRIPTION
**Pull request by Wolverinoid**

### CODE REVIEW

**Comment by ls-initiatives** [comment]
Fixes #521
Works for me on Ubuntu Jammy beta
Thanks

**Comment by gclough** [comment]
@Wolverinoid thanks for the Pull Request.  I have triggered the pipeline, and will check back later to see if it completes.

**Comment by gclough** [comment]
@Wolverinoid, it seems that fedors33 is causing problems with the CI pipeline... so I've done a bit of a cleanup with #528

Once that merges, could you rebase to get the pipeline running?

**Review by halvaborsch — COMMENTED** [review]
We need 14 version here
https://github.com/Wolverinoid/postgresql/blob/add_postgresql14_support/defaults/main.yml#L49

**Comment by rimad37** [comment]
The following parameter "postgresql_extension_destdir: ""  # (>= 14)" seems to cause trouble for pgsql 14 in Centos 8.2.

pgsql

**Comment by walbertus** [comment]
any update on this? looking forward to support for pg 14

**Comment by MrMegaNova** [comment]
PG 14 is now supported

**Pull request closed without merging**
