### PR TITLE
Ubuntu 20 (Focale Fossa) support

### LINKED ISSUE #464: User defined variable values got overriden by role `vars/*.yml` default one
Hi,

it seem the role force default vars in `main.yml`:

```
# file: postgresql/tasks/main.yml

- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/empty.yml"
  tags: [always]

#
# Override defaults/main.yml with PostgreSQL version specific values
#
- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/postgresql_{{ postgresql_version }}.yml"
    - "../vars/empty.yml"
  tags: [always]
...
```

Which cause user defined values to be overriden. (for example `postgresql_cluster_name`, `postgresql_unix_socket_directories`)

Example:

```
#file modified roles/anxs.postgresql/tasks/main.yml

- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/empty.yml"
  tags: [always]

#
# Override defaults/main.yml with PostgreSQL version specific values
#
- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/postgresql_{{ postgresql_version }}.yml"
    - "../vars/empty.yml"
  tags: [always]

- debug:
    msg: "role debug: {{ postgresql_cluster_name }} {{ postgresql_unix_socket_directories }}"
```
```
# file group_vars/postgresql.yml
postgresql_cluster_name: "my_cluster"
postgresql_pid_directory: "/var/run/postgresql/{{ postgresql_cluster_name }}/{{ postgresql_version }}"
postgresql_unix_socket_directories:
  - "{{ postgresql_pid_directory }}"
```
```
# file my_playbook.yml
- name: "Ensure databases are configured"
  hosts: databases
  pre_tasks:
    - debug:
        msg: "pre tasks playbook debug: {{ postgresql_cluster_name }} {{ postgresql_unix_socket_directories }}"
  roles:
    - anxs.postgresql
  post_tasks:
    - debug:
        msg: "post tasks playbook debug: {{ postgresql_cluster_name }} {{ postgresql_unix_socket_directories }}"
```

output: 

```
...
TASK [debug] *********************************************************************************************************************************************************************************************************************************

ok: [db] => {
    "msg": "pre task playbook debug: my_cluster [u'/var/run/postgresql/my_cluster/10']"
}

...

TASK [anxs.postgresql : debug] ***************************************************************************************************************************************************************************************************************

ok: [db] => {
    "msg": "role debug: data [u'/var/run/postgresql/data/10', u'/tmp']"
}

...

TASK [debug] *********************************************************************************************************************************************************************************************************************************

ok: [db] => {
    "msg": "post task playbook debug: data [u'/var/run/postgresql/data/10', u'/tmp']"
} 
... 
```

I may be wrong, but i think it's not intended to force user defined values to default one ;)

Is there a way i did not see to disable that or do we have to submit a fix ?

For my roles, I tend to add "__" prefix to role's vars to avoid name collision and if i need to set variables to default values if they are not set by the user i use that:
```
- name: "Some task description"
  set_fact:
    some_role_variable: "{{ __some_role_variable_default_value }}"
  when: some_role_variable is not defined
```

Ansible version used: ansible 2.7.0

Best regards.

### PR DESCRIPTION
**Pull request by thbar**
This mimics #435 but for Ubuntu 20 instead of Ubuntu 18.

To be considered a WIP.

I believe it would ultimately be better to first fix #464, then make it easy to override that from the user side, but at least this can help some!

### CODE REVIEW

**Comment by gclough** [comment]
@thbar , could you get this working with travis, et?  Any new OS needs to have CI testing to ensure everything is working properly.

**Comment by thbar** [comment]
@gclough I will have a look at this, since my migration budget is soon to arrive :-)

**Comment by thbar** [comment]
Upgrade budget still not coming. Situation is complicated.

**Comment by maglub** [comment]
If you merge ANXS:master into your fork, you will get CI testing as per #511 in Github Actions. We have an Ubuntu 20 CI test running now.

**Comment by thbar** [comment]
I have refreshed my fork, closed the PR and reopened it to force a CI run.

**Comment by thbar** [comment]
The installation seems to work locally with a refreshed fork, and I get the correct version of PostGIS installed.

The CI fails though (at least on Debian 10):

```
TASK [postgresql : PostgreSQL | Reload all conf files] *************************
668
  changed: [postgresql-11]
669
  changed: [postgresql-12]
670
  fatal: [postgresql-10]: FAILED! => {"changed": false, "msg": "Unable to start service postgresql: Job for postgresql.service failed because the control process exited with error code.\nSee \"systemctl status postgresql.service\" and \"journalctl -xe\" for details.\n"}
671
  changed: [postgresql-13]
672
  changed: [postgresql-9_6]
```

I cannot tell yet if this is a transient CI error, or something linked to the PR. I'll close and reopen again.

**Comment by thbar** [comment]
It was a transient error, good!

Something is still missing to properly test this: since the suite wasn't failing before the PR, this means the modified code path is not under test.

Testing this would require to install some version of PostGIS during the tests.

**Comment by thbar** [comment]
@gclough I am using this at the moment (in Vagrant instances), so far so good.

**Comment by thbar** [comment]
@gclough thanks for incorporating this!

**Pull request merged**
