### PR TITLE
[9.3 + 9.4] One 'postgresql.conf' template per version  of  PostgreSQL

### LINKED ISSUE #47: 9.4 won't start because of krb_srvname deprecation
Here's console output

```
$ /usr/lib/postgresql/9.4/bin/postgres -d 3 -D /var/lib/postgresql/9.4/main -c config_file=/etc/postgresql/9.4/main/postgresql.conf
LOG:  unrecognized configuration parameter "krb_srvname" in file "/etc/postgresql/9.4/main/postgresql.conf" line 80
FATAL:  configuration file "/etc/postgresql/9.4/main/postgresql.conf" contains errors
DEBUG:  shmem_exit(1): 0 before_shmem_exit callbacks to make
DEBUG:  shmem_exit(1): 0 on_shmem_exit callbacks to make
DEBUG:  proc_exit(1): 0 callbacks to make
DEBUG:  exit(1)
```

### PR DESCRIPTION
**Pull request by sebalix**
Hi,

This PR adds one 'postgresql.conf' file per version (9.3 + 9.4 here, previous versions could be added later). These files are the upstream ones, updated with the ``{{postgresql_*}}`` variables.

It fixes #47, and adds other options which were missing for the 9.3 version (``autovacuum_multixact_freeze_max_age``, ``vacuum_multixact_freeze_min_age`` and ``vacuum_multixact_freeze_table_age``).

Regards,

### CODE REVIEW

**Comment by clonedagain** [comment]
:+1: the role does allow deploying PG9.4 for the moment.

**Comment by clonedagain** [comment]
@sebalix at this stage, the best would be to provide one template config file per version (`postgresql.conf-9.1.j2` ; `postgresql.conf-9.2.j2` ; ..) and change the config task to:
```
- name: PostgreSQL | Update configuration - pt. 2 (postgresql.conf)
  template:
  src: postgresql.conf-{{postgresql_version}}.j2
  ...
```
Would you care to try this?

**Comment by sebalix** [comment]
I agree, I prefer to do it this way too.

**Comment by pjan** [comment]
+1 for that solution @clonedagain. Opens it up to also target 9.3

**Comment by sebalix** [comment]
PR updated. Upstream configuration files have been added too (taken from the packages), it helps to compare the changes brought by next versions.

**Comment by clonedagain** [comment]
Almost working...
Using pg 9.4 I still get a nonfunctional instance because the config file contains `session_preload_libraries = '[]'`

**Comment by sebalix** [comment]
Rebased and fixed

**Comment by clonedagain** [comment]
:+1: for me

**Comment by pjan** [comment]
Works for me.

Quite interesting to put the `.orig` files in it as well, where I used to copy everything in the defaults. Makes sense when you start supporting different versions.

@farridav has been spending some time on this role last week, so would be happy to also see his :ok:

**Comment by sebalix** [comment]
Once this PR merged, I will do some other to support the previous versions, especially the 9.1.

**Comment by dukz** [comment]
Hello, wondering if there is any schedule for a release of this feature?

**Comment by pjan** [comment]
@farridav care to review? If not, I will merge this in

**Comment by sebalix** [comment]
Hi,
Any feedback on this?

**Comment by farridav** [comment]
Cool, I will take a look at this first thing tomorrow morning, 9am GMT and see if i can review :smile:

**Comment by farridav** [comment]
Actually just had a quick look through this, looking good.. and great to see we are testing multiple versions. I would still like another quick look tomorrow where ill test it then hopefully a merge. Great work guys!

**Comment by farridav** [comment]
Cool, I've had a look through, seems sane to me, I’ve tested both postgres versions :smile: we are unable to move from one to the other, but I think that’s not something we support anyhow.. 

Once rebased I'm happy to merge

It needs a rebase against master, conflicts are with `.travis.yml`.. To save me putting a PR into yours, here is the resolved file:

```
---

language: python
python: "2.7"
env:
  - POSTGRESQL_VERSION=9.3
  - POSTGRESQL_VERSION=9.4
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt python-pycurl locales
  - echo 'en_US.UTF-8 UTF-8' | sudo tee /var/lib/locales/supported.d/local
install:
  - pip install ansible==1.6.2
script:
  - echo localhost > inventory
  - ansible-playbook -i inventory test.yml --syntax-check
  - ansible-playbook -i inventory test.yml --connection=local --sudo -e "postgresql_version=$POSTGRESQL_VERSION"
  - >
    ansible-playbook -i inventory test.yml --connection=local --sudo -e "postgresql_version=$POSTGRESQL_VERSION"
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
```

**Comment by sebalix** [comment]
Thanks, I will make a rebase today ASAP.

**Comment by farridav** [comment]
LGTM

**Comment by onlydole** [comment]
Any word on when the Ansible Galaxy Repo will be updated for this issue?

**Comment by farridav** [comment]
I Will get a release put out tomorrow morning, ab 10AM GMT :smile:

**Comment by farridav** [comment]
I have put up a release for this, the tag is [v1.1.2](https://github.com/ANXS/postgresql/tree/v1.1.2) :+1:

**Comment by onlydole** [comment]
Thank you @farridav!

**Comment by pjan** [comment]
:smile: thx @farridav

**Comment by dukz** [comment]
Thanks guys. Needed this. :)

**Pull request merged**
