### PR TITLE
Fedora support

### PR DESCRIPTION
**Pull request by jlozadad**
Added fedora image to vagrantfile
added extra vars for fedora in defaults/main.yml
added a fedora.yml

### CODE REVIEW

**Comment by jlozadad** [comment]
would like to hear feedback is there a better way to use the same vars and still use fedora or having seperate vars is the best way.

**Comment by jlozadad** [comment]
#324

**Comment by jlozadad** [comment]
merging this PR to add fedora support. The only thing failing is installing version 9.3 but, for fedora that version does not exist.

**Comment by gclough** [comment]
@jlozadad , I've checked with Devrim (the PostgreSQL packager), and there will never be a PostgreSQL v9.3 version for Fedora.  To get the Travis tests working, can we either:

1) Figure out how to selectively skip testing of v9.3 on Fedora
2) Remove travis tests for Fedora

**Pull request merged**
