### PR TITLE
Error when installing as a user other than 'root'

### PR DESCRIPTION
**Pull request by VitorHP**
I'm using another user (which is also a sudoer) to run the playbook. when it tries to get the apt-key, the run fails with:

```
TASK: [ANXS.postgresql | PostgreSQL | Add PostgreSQL repository apt-key] ****** 
<54.187.60.240> ESTABLISH CONNECTION FOR USER: ubuntu
<54.187.60.240> REMOTE_MODULE apt_key id=ACCC4CF8 state=present url=https://www.postgresql.org/media/keys/ACCC4CF8.asc
<54.187.60.240> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/vitorhp/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 54.187.60.240 /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1428783473.0-178963347232152 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1428783473.0-178963347232152 && echo $HOME/.ansible/tmp/ansible-tmp-1428783473.0-178963347232152'
<54.187.60.240> PUT /tmp/tmpYo7GAO TO /home/ubuntu/.ansible/tmp/ansible-tmp-1428783473.0-178963347232152/apt_key
<54.187.60.240> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/vitorhp/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 54.187.60.240 /bin/sh -c 'LANG=C LC_CTYPE=C /usr/bin/python /home/ubuntu/.ansible/tmp/ansible-tmp-1428783473.0-178963347232152/apt_key; rm -rf /home/ubuntu/.ansible/tmp/ansible-tmp-1428783473.0-178963347232152/ >/dev/null 2>&1'
failed: [54.187.60.240] => {"cmd": "apt-key add -", "failed": true, "rc": 1}
stdout: ERROR: This command can only be used by root.
```

Do you think is reasonable to add a `sudo: yes` to the tasks that may fail due to this kind of thing?

If you think so, i could make a PR.

### CODE REVIEW

**Comment by jgornick** [comment]
Thoughts on introducing a ```postgresql_sudo_user``` variable and using that user for all sudo tasks? There are instances where there's a sudo user for setting up vs service users set specifically to run services.

**Comment by soupdiver** [comment]
That's a very good point to add `sudo: yes` to the tasks needing it.
I like that approach more than executing everything with `sudo` permissions.

@VitorHP could update the PR against the latest master?

@jgornick I don't think we need an extra variable for this. You could overwrite the `sudo_user` when including the role.

**Comment by VitorHP** [comment]
@soupdiver Done

**Comment by soupdiver** [comment]
:+1: 
@otakup0pe @farridav

**Comment by jlozadad** [comment]
Looks like this PR is old and can be closed.

**Pull request closed without merging**
