### PR TITLE
Add support for PostgreSQL 9.1 and 9.2.

### LINKED ISSUE #21: Fails on earlier PostgreSQLs
I'm installing a 9.1 installation on an older Ubuntu machine. The following postgresql.conf config parameters are invalid but are included anyways:

#unix_socket_directories = '{{postgresql_unix_socket_directories|join(',')}}'
#unix_socket_group       = '{{postgresql_unix_socket_group}}'
#unix_socket_permissions = {{postgresql_unix_socket_permissions}}

#ssl_cert_file           = '{{postgresql_ssl_cert_file}}'
#ssl_key_file            = '{{postgresql_ssl_key_file}}'
#ssl_ca_file             = '{{postgresql_ssl_ca_file}}'
#ssl_crl_file            = '{{postgresql_ssl_crl_file}}'

#temp_file_limit = {{postgresql_temp_file_limit}}

#wal_sender_timeout = {{postgresql_wal_sender_timeout}}

#wal_receiver_timeout = {{postgresql_wal_receiver_timeout}}

#enable_indexonlyscan = {{'on' if postgresql_enable_indexonlyscan else 'off'}}

#event_source             = '{{postgresql_event_source}}'

#track_io_timing           = {{'on' if postgresql_track_io_timing else 'off'}}

#lock_timeout                   = {{postgresql_lock_timeout}}

Additionally, it's looking for the postgis package in the wrong place on Ubuntu 13.04:

Does not work on 13.04
    - "postgresql-{{postgresql_version}}-postgis-{{postgresql_ext_postgis_version}}"

Does work
    - "postgresql-{{postgresql_version}}-postgis"

### PR DESCRIPTION
**Pull request by sebalix**
This PR:
- add support for PostgreSQL 9.1 (`postgresql.conf.9.1.orig` + `postgresql.conf.9.1.j2`)
- add support for PostgreSQL 9.2 (`postgresql.conf.9.2.orig` + `postgresql.conf.9.2.j2`)
- update the `defaults/main.yml` file (add related version options, and add some `(>= 9.X)` or `(<= 9.X)` comments)
- update the Travis CI configuration:
  * remove all the pre-installed PostgreSQL servers in the Travis environment
  * reduce the `shared_buffers` value to 32Mb instead of 128Mb (default), otherwise PostgreSQL 9.1 and 9.2 don't start on Travis
- add a HOWTO explaining the general method I use to add a new PostgreSQL version

Fix #21

### CODE REVIEW

**Comment by farridav** [comment]
@sebalix role based testing has been merged in..

**Comment by sebalix** [comment]
@farridav thank you, I will fix this PR soon.

**Comment by sebalix** [comment]
PR Rebased

**Comment by sebalix** [comment]
PR Rebased

**Comment by sebalix** [comment]
Rebased

**Comment by farridav** [comment]
Looking at this today

**Comment by sebalix** [comment]
Thank you!

**Comment by farridav** [comment]
Im getting the following error:
```
TASK: [postgresql | PostgreSQL | Restart PostgreSQL] ************************** 
failed: [anxs.local] => {"failed": true}
msg:  * Stopping PostgreSQL 9.1 database server
   ...done.
 * Starting PostgreSQL 9.1 database server
 * The PostgreSQL server failed to start. Please check the log output:
2015-12-15 11:50:37 UTC FATAL:  could not create shared memory segment: Invalid argument
2015-12-15 11:50:37 UTC DETAIL:  Failed system call was shmget(key=5432001, size=41205760, 03600).
2015-12-15 11:50:37 UTC HINT:  This error usually means that PostgreSQL's request for a shared memory segment exceeded your kernel's SHMMAX parameter.  You can either reduce the request size or reconfigure the kernel with large
r SHMMAX.  To reduce the request size (currently 41205760 bytes), reduce PostgreSQL's shared memory usage, perhaps by reducing shared_buffers or max_connections.
        If the request size is already small, it's possible that it is less than your kernel's SHMMIN parameter, in which case raising the request size or reconfiguring SHMMIN is called for.
        The PostgreSQL documentation contains more information about shared memory configuration.
   ...fail!
```

When trying to setup postgres 9.1... heres the diff https://github.com/ANXS/postgresql/compare/farridav/test_with_vars...farridav/test_postgres_91 

you will see i have added `postgresql_shared_buffers: 32MB` within tests/vars.yml but its not alleviating the issue.... if you see something ive missed let me know... ill carry on playing with it..

**Comment by farridav** [comment]
Keen to try and get this in tomorrow if possible, I will try and get things working tonight

**Comment by farridav** [comment]
Got this working, had to lower my shared memory to 20mb.. It's because I'm running it inside the VM, which has a low default memory allocation.. With any luck I'll get this in tonight

**Comment by farridav** [comment]
After having a proper run through with both 9.1 and 9.2, all looks good to me..

**Comment by sebalix** [comment]
Sorry, a bit late... Thank you for your work!

**Pull request merged**
