### PR TITLE
add citext extension support

### PR DESCRIPTION
**Pull request by sh**

### CODE REVIEW

**Comment by sh** [comment]
It's just a clone of uuid_ossp, seems like the most complete approach. 
Other extensions don't have proper ````failed_when```` and ````changed_when```` definitions.

I don't mind to adjust as mentioned, just give me a sign and I'll update the PR.

**Comment by soupdiver** [comment]
I would appreciate that to stay uniform :)

**Comment by sh** [comment]
@soupdiver done :)

**Comment by soupdiver** [comment]
LGTM
@pjan @otakup0pe @farridav

**Comment by farridav** [comment]
Seems fine to me

**Pull request merged**
