### PR TITLE
Postgres13

### PR DESCRIPTION
**Pull request by niccolox**
hopefully a MVP Postgres 13 PR tested on Ubuntu 20.04

### CODE REVIEW

**Comment by maglub** [comment]
It breaks here, since you commented away the `postgresql_wal_keep_segments` variable in `defaults/main.yml`. Any particular reason you don't want the variable set?

image

**Comment by gclough** [comment]
I already have this done in #504 , but it needs some help with the debian8 install as it doesn't support PostgreSQL v13.

**Comment by niccolox** [comment]
@gclough your PR looks more complete, I just pushed what I had that worked for me

@maglub happy to close off my PR in reference to https://github.com/ANXS/postgresql/pull/504

**Comment by gclough** [comment]
OK, let's close this and concentrate on #504.  It needs a review, so if anyone can check it I'd appreciate the extra pair(s) of eyes.

**Pull request closed without merging**
