### PR TITLE
Add support for RHEL 8

### PR DESCRIPTION
**Pull request by Chilinot**
Tested manually on CentOS 8 server. Needs proper testing, but seems to work fine now.

Solves #471

### CODE REVIEW

**Comment by Chilinot** [comment]
The tests failed because in RHEL8 they no longer setup python by default as they no longer wanted to pick a default python version. I fixed it by installing python3 and linking `/usr/bin/python`.

**Comment by Chilinot** [comment]
Now it fails because there are locale issues. Why is systemd disabled in the docker image?

**Comment by Chilinot** [comment]
The Centos:8 image does not bundle locales by default, causing the issues noted here.

**Comment by maglub** [comment]
I like the approach in this pull request, and we should port it to use molecule, as soon as we have pullet that merge request. I will be back in a day or so.

**Comment by maglub** [comment]
You are on the right way. I just cloned your project and ran a test:

```
git clone https://github.com/scrive/postgresql.git postgresql.scrive
cd postgresql.scrive
git checkout support-centos8
MOLECULE_DISTRO=centos8 molecule destroy
MOLECULE_DISTRO=centos8 molecule converge

...
TASK [postgresql : PostgreSQL | Install PostgreSQL | dnf] **********************
fatal: [postgresql-9_6]: FAILED! => {"changed": false, "msg": "Failed to download metadata for repo 'postgresql': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried", "rc": 1, "results": []}
fatal: [postgresql-12]: FAILED! => {"changed": false, "msg": "Failed to download metadata for repo 'postgresql': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried", "rc": 1, "results": []}
fatal: [postgresql-10]: FAILED! => {"changed": false, "msg": "Failed to download metadata for repo 'postgresql': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried", "rc": 1, "results": []}
fatal: [postgresql-13]: FAILED! => {"changed": false, "msg": "Failed to download metadata for repo 'postgresql': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried", "rc": 1, "results": []}
fatal: [postgresql-11]: FAILED! => {"changed": false, "msg": "Failed to download metadata for repo 'postgresql': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried", "rc": 1, "results": []}
```

If you locally run the `MOLECULE_DISTRO=centos8 molecule destroy` once, then run `MOLECULE_DISTRO=centos8 molecule converge` until you get through your playbook, you will save a lot of time testing on your side (since you only test against centos8).

**Comment by maglub** [comment]
Looks good to me! You should also update the README.md table and add green checks for Centos8.

**Comment by maglub** [comment]
I think this looks good. What about you, @gclough ?

**Pull request merged**
