### PR TITLE
Making changing of locale easier

### PR DESCRIPTION
**Pull request by farridav**
Setting all of the `postgresql_lc_*` vars to that of `postgresql_locale` so you need only change locale in one variable..

### CODE REVIEW

**Comment by sebalix** [comment]
What about setting the `postgresql_lc_*` options with the value of `postgresql_locale` in `defaults/main.yml`?
```
postgresql_lc_messages: "{{ postgresql_locale }}"
postgresql_lc_monetary: "{{ postgresql_locale }}"
postgresql_lc_numeric: "{{ postgresql_locale }}"
postgresql_lc_time: "{{ postgresql_locale }}"
```
This way, we just need to change the `postgresql_locale` option (and eventually `postgresql_lc_*` for special configurations).

**Comment by farridav** [comment]
yeah I had thought about that too.. is it a common use case to want say `postgresql_lc_messages` in a different locale to that of your databases? if not, or if it is acceptable for a user to override that var specifically.. that may be an easier change to make...

**Comment by sebalix** [comment]
For a default configuration, it is easier for the user. I don't think this is common as you say to change such settings, but for those who need such configuration, they can override the `postgresql_lc_*` options.

**Comment by farridav** [comment]
@sebalix agreed.. and updated :) feel free to merge on green

@goetzk ^

**Comment by sebalix** [comment]
@farridav I do not have commit rights, I'm just a contributor :)

**Comment by goetzk** [comment]
@farridav Thanks.

**Pull request merged**
