### PR TITLE
Support PostgreSQL v11 early alpha

### PR DESCRIPTION
**Pull request by gclough**
The PostgreSQL v11 very early alpha release is available, but should only be used for crash testing.  It installs and runs, but should not be used for any production work.

### CODE REVIEW

**Comment by gclough** [comment]
It seems that the Debian URL doesn't work, even if I use the "-testing" suffix as recommended:

https://wiki.postgresql.org/wiki/Apt/FAQ#Development_snapshots

I'll work on that a bit later, but if someone with Debian skills could help out I would appreciate it.  The build works on CentOS.

**Comment by jlozadad** [comment]
is this step needed at all?
```
ASK [Gathering Facts] *********************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TimeoutError: Timer expired after 10 seconds
fatal: [postgresql-9.6]: FAILED! => {"changed": false, "cmd": "/bin/lsblk --list --noheadings --paths --output NAME,UUID --exclude 2", "msg": "Timer expired after 10 seconds", "rc": 257}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TimeoutError: Timer expired after 10 seconds
fatal: [postgresql-9.4]: FAILED! => {"changed": false, "cmd": "/bin/lsblk --list --noheadings --paths --output NAME,UUID --exclude 2", "msg": "Timer expired after 10 seconds", "rc": 257}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TimeoutError: Timer expired after 10 seconds
fatal: [postgresql-9.3]: FAILED! => {"changed": false, "cmd": "/bin/lsblk --list --noheadings --paths --output NAME,UUID --exclude 2", "msg": "Timer expired after 10 seconds", "rc": 257}
ok: [postgresql-11]
```
seems to fail a lot in some areas. Fails on my fedora test.

**Comment by gclough** [comment]
The failure I see is mostly in:

`TASK [ANXS.postgresql : PostgreSQL | Install PostgreSQL] ***********************`

There's something broken in the Ubuntu/Debian packages at the moment, but the developers tell me that they have been released already.  I need to figure out why the apt repository URL doesn't work.

As for your error during `ASK [Gathering Facts]`... that's an internal part of Ansible, right?  That step happens before even the first `include_vars` in the `tasks/main.yml`... so I'm not sure how I could influence it.  Strange...

**Comment by jlozadad** [comment]
ill have to investigate further. i though i saw somewhere else a similar command was run and failed. i could had mistaken it.

**Comment by gclough** [comment]
Rebased in #405 , so this can likely die once that's merged.

**Comment by gclough** [comment]
Superseded by #405

**Pull request closed without merging**
