### PR TITLE
Fix postgis package names for issue #156

### PR DESCRIPTION
**Pull request by jalessio**
Addresses misnamed postigs package names. Issue identified and solution proposed in issue #156.

### CODE REVIEW

**Comment by macnibblet** [comment]
I could really use this :+1:

**Comment by scotbond** [comment]
Why is this not being merged? common, its just an annoying typo. is this repo alive?

**Comment by sebalix** [comment]
Some details: `postgresql-9.X-postgis-Y.Z-scripts` (starting from 9.0) are transitional dummy packages and are replaced by `postgresql-9.X-postgis-scripts` ones. This PR can be safely merged.

**Comment by lhoss** [comment]
👍  (plz merge .. many active forks have that change!)

**Comment by otakup0pe** [comment]
Oh I merged https://github.com/ANXS/postgresql/pull/164 instead... 

The delay on merging is related to a need for additional maintainers, especially on this role. Kindly let me know if y'all have availability to help.

**Pull request closed without merging**
