### PR TITLE
Increase the travis test coverage to include popular options

### LINKED ISSUE #304: Test more options in travis (e.g. tuning)
At present we only test the basic install with travis, but we should try various other options such as:

* Create Database
* Create Extensions
* Tuning  (pgtune... or #301 , once it's merged)

### PR DESCRIPTION
**Pull request by gclough**
Fixes #304 

Added extra checks for:
```
postgresql_databases="travis_test_database"
postgresql_database_extensions="adminpack,pgcrypto"
postgresql_users="travis_test_user1, travis_test_user2"
postgresql_ext_install_contrib=true
postgresql_ext_install_postgis=true
postgresql_pgtune=true
```

### CODE REVIEW

**Comment by gclough** [comment]
Not everything works everywhere... so I've trimmed some of the options:

postgresql_databases="travis_test_database"
postgresql_database_extensions="adminpack,pgcrypto"
postgresql_users="travis_test_user1, travis_test_user2"
postgresql_ext_install_contrib=true
postgresql_ext_install_postgis=false
postgresql_pgtune=true

pgtune will fail on v9.5 and later... but we can fix that once #301 is merged.

**Comment by gclough** [comment]
@jlozadad , I can't figure out why Travis fails here.  I can copy/paste the JSON parameters and it runs just fine...

Any ideas?

**Comment by UnderGreen** [comment]
@gclough You use a wrong way to test these things. Add all that stuff to `tests/docker/group_vars/postgresql.yaml` and delete new lines in `.travis.yaml`.

**Comment by gclough** [comment]
@UnderGreen ... I understand.  What I was trying to do was multiple tests:

1) Test with default parameters
2) Test with lots of extended settings

I guess if we just test with everything turned on, then that's a pretty good test.  I've removed the travis bits, but just in case we want them later, here they are:

```
  # Play test
  - ansible-playbook -i tests/docker/hosts -e image_name=${IMAGE_NAME} tests/docker/site.yml

  # Idempotence test
  - ansible-playbook -i tests/docker/hosts -e image_name=${IMAGE_NAME} tests/docker/site.yml > idempotence_out
  - ./tests/idempotence_check.sh idempotence_out

  # Play test - Extended Options
  - ansible-playbook -i tests/docker/hosts -e image_name=${IMAGE_NAME} tests/docker/site.yml --extra-vars 'postgresql_ext_install_contrib=true postgresql_ext_install_postgis=false postgresql_pgtune=false postgresql_ssl=false'

  # Idempotence test
  - ansible-playbook -i tests/docker/hosts -e image_name=${IMAGE_NAME} tests/docker/site.yml --extra-vars 'postgresql_ext_install_contrib=true postgresql_ext_install_postgis=false postgresql_pgtune=false postgresql_ssl=false' > idempotence_out
  - ./tests/idempotence_check.sh idempotence_out
```

**Comment by gclough** [comment]
@UnderGreen , this now works, but the only additional test was installing the `contrib` stuff.  The others can't be enabled yet, but I have other pull requests that should fix most of them... and once they are merged, then we can enable all of these tests to increase our coverage.

**Comment by sebalix** [comment]
@gclough Can you squash your commits ?
I have to say great work for all your PRs to improve/fix this role, I hope they will be merged soon.

**Comment by gclough** [comment]
Thanks @sebalix .  I know a lot about PostgreSQL... but not so much about Git, so thanks for your advice.  I think I've squashed the commits, but if that's not right then please let me know.

**Pull request merged**
