### PR TITLE
Migrate from Travis CI to GitHub actions

### PR DESCRIPTION
**Pull request by maglub**
Hi,

This one obsoletes https://github.com/ANXS/postgresql/pull/510, as I have been continuing the Molecule implementation with:

* Disable .travis-ci.yml
* Added github actions

image

### CODE REVIEW

**Comment by gclough** [comment]
Thanks for the work @maglub .  The Travis pipeline still seems to run, and where can I see the Molecule CI tests?

image

**Comment by maglub** [comment]
I have pushed a delete of the .travis-ci.yml file, so it no longer runs in this pull request.

I just can't figure out how to make it run in a pull request in this repo. It works in my fork, in the `github-actions` branch.

https://github.com/maglub/postgresql/actions/runs/661254762

The molecule tests are found in the `./molecule` directory in this pull request.

I will test a couple of more things.

**Comment by maglub** [comment]
I just tested on a separate repo that I set up here: https://github.com/maglub/actiontest/actions and could reproduce this behavior.

The empty project did not have a github actions configuration, only a README.md file. I forked the project, and added a `.github/workflow/ci.yml`, and created a pull reqeust.

* The pull request did not run any tests (the test was a simple `ls -la`
* I merged the first pull reqeust, which triggered a Github Actions test run.

Then went ahead and changed the test to do the following:

```
      - name: Simple test
        run: echo 2nd pull request
```

* Created a new pull request, which automatically started a Github Action test run.
* The new test run reflected the changed test in `.github/workflow/ci.yml`

So I think we need to decide whether we want to migrate to Github Action (or do both Travis CI and Github Actions for a while).

* If we want to skip Travis CI, we could just merge this PR.
* If we want to run for a while in parallell, we should add the deleted .travis-ci.yml file again.

I do not have an Ansible Galaxy notification (as we have in .travis-ci.yml) yet. I am not sure yet if

**Comment by thbar** [comment]
Just wanted to comment: superbe work, it will help the role tremendously I believe! Thank you ❤️

**Comment by maglub** [comment]
I will merge this pull request later today, unless @gclough or @otakup0pe has any objections.

**Pull request merged**
