### PR TITLE
Crosscheck, and fix all missing parameters, defaults, etc.

### LINKED ISSUE #314: log_replication_commands parameter missing from v9.5, and v9.6
The `log_replication_commands` parameter is missing from the v9.5, and v9.6 configuration.  It should be added to the `templates/postgresql.conf.9.[56].j2` files, and unless PR #267 is merged... then it should be added to the `defaults/main.yml` too.

### PR DESCRIPTION
**Pull request by gclough**
Fixed #314 

Looking around, there seems to have been some missing parameters and defaults.  I've crosschecked them, and updated the ones I found.  I believe this is a complete verification.  There are comments in #314 explaining what I did to verify this.

It looks like a lot of changes, but they are mostly repeats across several files.

### CODE REVIEW

**Comment by gclough** [comment]
@sebalix ... not a problem.  I thought that merging in the master branch, and manually fixing any conflicts was the right thing to do.  I'll have to do some more reading, as git is a bit new to me.

**Comment by sebalix** [comment]
@gclough A merge has a strong semantic and it should be used to merge a work into a main branch (and so we keep the information that a feature/important change has been merged at a given date), but for keeping a development branch up-to-date with the main branch, rebase is the right tool to use.
I know git is not a simple tool and messing up a local repository is easy for a beginner (that's why I prefer Mercurial personally in some cases ;) ).
If you want some help to make a rebase on a PR, ping me, I could help you with that.

**Comment by gclough** [comment]
@sebalix ... it's _"rebased"_... but I'm guessing I've cocked that up entirely. :o(  How can I get in touch?

**Comment by sebalix** [comment]
@gclough what commands did you go exactly?
As this PR already contains a merge commit, we have to delete it when performing the rebase.
I will try that locally and tell you how to fix this PR step by step.

**Comment by gclough** [comment]
I tried this:

```
git checkout add_missing_conf_parameters
git rebase master
git rebase --continue
git status
git add defaults/main.yml
git rebase --continue
git commit -a
git push origin add_missing_conf_parameters
```

That said that gave me an error:

```

git pull upstream master
git pull upstream master
git commit -a
git pull upstream master
git push origin add_missing_conf_parameters
git branch
git checkout master
git pull upstream master
git push origin master
git checkout add_missing_conf_parameters 
git push origin add_missing_conf_parameters
git pull origin master
git push origin add_missing_conf_parameters
git pull origin master
git pull upstream master
git rebase
git rebase master
git rebase --abort
git rebase master
git rebase --continue
git status
git add defaults/main.yml
git rebase --continue
git add defaults/main.yml
git rebase --continue
git status
git rebase --continue
git branch
git add -a
git status
git rebase --continue
git rebase --skip
git rebase --continue
git add defaults/main.yml
git rebase --continue
git status
git branch
git commit -a
git push origin add_missing_conf_parameters
git pull upstream master
git pull origin add_missing_conf_parameters
git commit -a
git push origin add_missing_conf_parameters
git log -50
git log -50 | grep -lix
git log -50 | grep -i lix
git log -50
git log -50 | grep -i alix
git status
git reset --soft HEAD~9
git merge --squash HEAD@{1}
git commit -a
git push origin add_missing_conf_parameters
git pull origin add_missing_conf_parameters
git push origin add_missing_conf_parameters
git branch
git checkout master
git rebease
git rebase
git pull upstream master
git merge
git rebase -i
git checkout fix_postgis_on_centos 
git rebase master
git rebase --continue
git add tests/docker/group_vars/postgresql.yml
git rebase --continue
git commit -a
git branch
git push origin fix_postgis_on_centos
git pull origin d4150d3092b2cec11e5113a5013b7c8fa372170d
git pull origin fix_postgis_on_centos
git add tests/docker/group_vars/postgresql.yml
git commit -a
git push origin fix_postgis_on_centos
```

**Comment by sebalix** [comment]
@gclough I sent you an email, did you get it (just to know)?

**Pull request closed without merging**
