### PR TITLE
Fix issue 464

### PR DESCRIPTION
**Pull request by lrk**
My proposal to fix issue #464 

I renamed all role internal `vars` with double underscore prefix, and set values in `defaults/main.yml`.
I also remove unnecessary version specific files as they all contain same values that is now set as default.

I didn't come with an elegant solution for default postgis dependencies so i create the `postgresql_ext_postgis_default_deps` list that is used when `__postgresql_ext_postgis_deps` will be undefined.

side note: i think that comment with ">= version number" are incorrect, they should be "<= version number" in most cases as i think it should be read as: "when current version <= version number ..."
(example: the `postgresql_jit` variable comment)

I had to set `login_unix_socket` and `--host` parameters to tasks connecting to server for admin purposes to fix connection errors too

### CODE REVIEW

**Comment by lrk** [comment]
It seem the build fail for ubuntu / debian, i'll check that tonight.

**Comment by gclough** [comment]
Hi @lrk , there is some good stuff in here, thanks.  As the build is failing, and to make it easier to review.  Would it be possible to break them down into a couple of PR's?

**Comment by lrk** [comment]
@gclough sure, all i need is some time to re-work on that.

**Comment by thbar** [comment]
I would love to see some progress on this one. I believe #464 is the most problematic part of this role right now, because it makes it hard to override bogus defaults, such as #489 or similar (if I understand the problem correctly!).

Happy to help out a bit here (testing etc), at least on Ubuntu 16/18/20.

**Pull request closed without merging**
